//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoguelikeSouls.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextData() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoguelikeSouls.Resources.TextData", typeof(TextData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 造型独特的卡塔利纳骑士头盔。
        ///
        ///重视荣誉的卡塔利纳骑士，
        ///对于被其他国家笑称为洋葱觉得很气愤。
        ///但是以高级技术所制成的凸曲表面，
        ///拥有极高的招架物理攻击效果。
        ///造型独特的卡塔利纳骑士铠甲。
        ///
        ///重视荣誉的卡塔利纳骑士，
        ///对于被其他国家笑称为洋葱觉得很气愤。
        ///但是以高级技术所制成的凸曲表面，
        ///拥有极高的招架物理攻击效果。
        ///造型独特的卡塔利纳骑士臂甲。
        ///
        ///重视荣誉的卡塔利纳骑士，
        ///对于被其他国家笑称为洋葱觉得很气愤。
        ///但是以高级技术所制成的凸曲表面，
        ///拥有极高的招架物理攻击效果。
        ///造型独特的卡塔利纳骑士腿甲。
        ///
        ///重视荣誉的卡塔利纳骑士，
        ///对于被其他国家笑称为洋葱觉得很气愤。
        ///但是以高级技术所制成的凸曲表面，
        ///拥有极高的招架物理攻击效果。
        ///地下墓地的圣骑士，里罗伊的头盔。
        ///
        ///据说很久以前，
        ///白教信徒中出现的第一位不死人，
        ///是位身穿黄金铠甲的圣骑士。
        ///
        ///圣骑士带上两件宝物：神许重锤及圣者盾，
        ///为探索诸神之地罗德兰而踏上旅程──
        ///白教的不死人使命从此开始。
        ///地下墓地的圣骑士，里罗伊的铠甲。
        ///
        ///据说很久以前，
        ///白教信徒中出现的第一位不死人，
        ///是位身穿 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string AllArmorDescriptions {
            get {
                return ResourceManager.GetString("AllArmorDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡塔利纳
        ///圣骑士
        ///黑暗
        ///山贼
        ///黑影
        ///黑铁
        ///斯摩
        ///传道者
        ///宠爱
        ///智慧
        ///荣耀
        ///成就
        ///探索
        ///石
        ///附结晶
        ///封印者
        ///红色
        ///蓓尔嘉
        ///黑色
        ///铁
        ///太阳纹
        ///锁子
        ///皮
        ///圣职
        ///太阳虫
        ///刺针
        ///铁制
        ///硬皮
        ///魔法师
        ///破布
        ///厚
        ///法里斯
        ///绘画守护者
        ///翁斯坦
        ///东方
        ///黄衣
        ///小偷
        ///黑皮
        ///旅行
        ///黑骑士
        ///幽暗
        ///古典
        ///魔女
        ///上级骑士
        ///流浪
        ///魔法铁匠
        ///大
        ///贤者
        ///旅行
        ///骑士
        ///肮脏
        ///染血
        ///圣女
        ///银骑士
        ///哈维尔
        ///黄铜
        ///金边黑
        ///巨偶
        ///游魂士兵
        ///钢铁
        ///游魂盗贼
        ///巴勒德尔
        ///游魂战士
        ///巨人
        ///黯影太阳王冠
        ///月光
        ///大王王冠
        ///大王
        ///烂麻袋
        ///贪欲者的
        ///王族
        ///父亲的
        ///母亲的
        ///孩子的
        ///牙猪
        ///石像鬼
        ///高阶圣职
        ///亚尔特留斯
        ///白瓷
        ///王的先锋
        ///戈夫
        ///守护者
        ///微笑
        ///切斯特
        ///肥大头颅
        ///肥大魔法师
        /// 的本地化字符串。
        /// </summary>
        public static string AllArmorNames {
            get {
                return ResourceManager.GetString("AllArmorNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Demon Firesage
        ///Stray Demon
        ///Asylum Demon
        ///Capra Demon
        ///Taurus Demon
        ///Iron Golem
        ///Executioner Smough
        ///Crossbreed Priscilla
        ///Moonlight Butterfly
        ///Pinwheel
        ///Sanctuary Guardian
        ///Knight Artorias
        ///Manus, Father of the Abyss
        ///Black Dragon Kalameet
        ///Centipede Demon
        ///Great Grey Wolf Sif
        ///Gravelord Nito
        ///Ceaseless Discharge
        ///Gaping Dragon
        ///Dragon Slayer Ornstein
        ///Chaos Witch Quelaag
        ///Seath the Scaleless
        ///Dark Sun Gwyndolin
        ///Bell Gargoyle
        ///Gwyn, Lord of Cinder
        ///Four Kings
        ///Bed of Chaos
        ///Solaire
        ///Siegmeyer
        ///Sieglinde        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string AllBossNames {
            get {
                return ResourceManager.GetString("AllBossNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solaire
        ///Siegmeyer
        ///Sieglinde
        ///Petrus
        ///Rhea
        ///Ingward
        ///Crestfallen
        ///Anastacia
        ///Kingseeker Frampt
        ///Darkstalker Kaathe
        ///Darkmoon Knightess
        ///Gwynevere
        ///Gwyndolin
        ///Giant Blacksmith
        ///Crossbreed Priscilla
        ///Blacksmith Vamos
        ///Patches
        ///Elizabeth
        ///Marvelous Chester
        ///Ciaran
        ///Hawkeye Gough
        ///Havel the Rock
        ///Prince Ricard
        ///Vince
        ///Dusk
        ///Iron Tarkus
        ///Beatrice
        ///Maneater Mildred
        ///Leeroy
        ///Kirk
        ///King Jeremiah
        ///Lautrec
        ///Griggs
        ///Big Hat Logan
        ///Laurentius
        ///Quelana
        ///Eingyi
        ///Nico
        ///Undead
        ///Andre
        ///Oswald
        ///Shiva
        ///Alvina
        ///Domnhall
        ///Cata [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string AllNPCNames {
            get {
                return ResourceManager.GetString("AllNPCNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础魔法,能射出灵魂箭灵魂箭具备法术属性的攻击力,
        ///因此对铁铠甲与坚硬的鳞片等,
        ///抗物理属性能力强的对手相当有效.
        ///“灵魂箭”的高阶魔法,
        ///能射出威力更强的灵魂箭在彼海姆的龙学院中,
        ///得要学会这项魔法,才算是独当一面的魔法师.
        ///更加重视威力的灵魂魔法,
        ///能射出灵魂巨箭为了提升威力而牺牲施放速度的魔法
        ///使用时会露出很大的破绽,且可用次数不多,
        ///是种不好运用的魔法.
        ///“灵魂巨箭”的高阶魔法,
        ///能射出威力更强的灵魂巨箭虽然不好运用这点依旧没变,
        ///但其威力足以弥补这种缺点,
        ///因此有部分魔法师经常使用.
        ///“大帽子”罗根的独门魔法,
        ///能射出追踪性能优异的灵魂块既然灵魂是生命之源,
        ///会受生命吸引自是理所当然
        ///从这魔法中,能一窥求知若渴的罗根为人.
        ///罗根借着在神的书库获得的庞大知识,
        ///更进一步强化性能的魔法
        ///能射出追踪性能优异的灵魂结晶块可见灵魂、结晶、魔法,
        ///这三者似乎有十分密切的关系.
        ///“大帽子”罗根的独门魔法,
        ///能射出具贯穿能力的灵魂枪这魔法象征罗根在战斗时的实力,
        ///也是在传说中常被提及,有如他的代名词般的魔法
        ///有人形容其威力就像葛温王的雷电一样.
        ///罗根借着在神的书库 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string AllSpellDescriptions {
            get {
                return ResourceManager.GetString("AllSpellDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灵魂箭
        ///强力灵魂箭
        ///灵魂巨箭
        ///强力灵魂巨箭
        ///追踪灵魂块
        ///追踪灵魂结晶块
        ///灵魂枪
        ///灵魂结晶枪
        ///法术武器
        ///强力法术武器
        ///结晶法术武器
        ///法术盾
        ///强力法术盾
        ///隐形武器
        ///隐形身躯
        ///光明照耀
        ///静音
        ///传声
        ///修理
        ///控制坠落
        ///拟态
        ///解咒
        ///治疗
        ///白龙吐息
        ///黑暗弹
        ///黑暗飞沫
        ///黑暗雾
        ///追踪者
        ///火球
        ///火焰弹
        ///大火球
        ///火焰风暴
        ///火焰大风暴
        ///喷射火焰
        ///横扫火焰
        ///引燃火焰
        ///引燃烈火
        ///毒雾
        ///猛毒雾
        ///喷射酸液
        ///铁身躯
        ///剧烈出汗
        ///魅惑不死人
        ///内在潜力
        ///混沌大火球
        ///混沌风暴
        ///混沌横扫火焰
        ///黑焰
        ///恢复
        ///大恢复
        ///限制大恢复
        ///阳光疗愈
        ///生命力涌现
        ///阳光滋润
        ///墓王剑舞
        ///墓王大剑舞
        ///归乡路
        ///原力
        ///诸神之怒
        ///原力并射
        ///寻求建言
        ///雷枪
        ///巨雷枪
        ///阳光之枪
        ///法术防护
        ///强化法术防护
        ///因果报应
        ///和平缓步
        ///沉默禁令
        ///阳光之剑
        ///暗月光之剑
        /// 的本地化字符串。
        /// </summary>
        public static string AllSpellNames {
            get {
                return ResourceManager.GetString("AllSpellNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 射出威力更强的灵魂箭
        ///射出灵魂巨箭
        ///射出威力更强的灵魂巨箭
        ///射出追踪性能优异的灵魂块
        ///射出追踪性能优异的灵魂结晶块
        ///射出具贯穿能力的灵魂枪
        ///射出具贯穿能力的灵魂结晶枪
        ///以法术强化右手武器
        ///以法术大幅强化右手武器
        ///以结晶法术大幅强化右手武器
        ///以法术强化左手盾牌
        ///以法术大幅强化左手盾牌
        ///够让右手武器变透明
        ///够让全身变得近乎透明
        ///够发出照亮周围的光线
        ///彻底消除施术者发出的所有声响
        ///在远处引发声响，吸引敌人注意
        ///够修理目前装备的武器、防具
        ///减轻坠落后的伤害，并降低坠落时发出的声响
        ///够变身成融入周遭环境的某种物品
        ///减缓诅咒累积状态
        ///减缓出血以及所有毒素累积，
        ///够喷出白龙希斯的结晶吐息
        ///放出巨大的黑暗弹
        ///连续施放黑暗弹
        ///释放黑暗雾
        ///将人性黑暗面暂时赋予意志施放
        ///掷出火球
        ///掷出火焰弹
        ///掷出巨大的火球
        ///在自身周围卷起数道火柱
        ///在自身周围卷起数道巨大火柱
        ///从手掌喷出火焰
        ///以火焰鞭横扫对手
        ///从手中引燃威力强大的火焰
        ///从手中引燃威力强大的烈火
        ///引发毒雾
        ///引发剧毒雾
        ///喷出损坏武器与防具的酸液
        ///魅惑不死人，使其暂时成为我方同伴
        ///暂时提升力气与耐力，但血量会 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string AllSpellSummaries {
            get {
                return ResourceManager.GetString("AllSpellSummaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 万能触媒【除错用／魔法奇迹两用】
        ///万能触媒【选单替身用】
        ///武器种类：短剑
        ///
        ///攻击属性：斩击／突刺
        ///
        ///
        ///
        ///标准短剑。
        ///
        ///小巧，攻击力低，但攻击速度快，可以连续攻击。
        ///
        ///格挡后或从背后使出致命一击的威力极高。
        ///
        ///
        ///
        ///有斩击及突刺两种攻击属性，
        ///
        ///足以应付各种情况。
        ///武器种类：短剑
        ///
        ///攻击属性：斩击／突刺
        ///
        ///
        ///
        ///专门用于格挡的短剑。
        ///
        ///通常装备于左手。
        ///
        ///
        ///
        ///因卡利姆骑士经常使用而闻名，
        ///
        ///卡利姆骑士的特征就是不拿盾。
        ///武器种类：短剑
        ///
        ///攻击属性：斩击／突刺
        ///
        ///
        ///
        ///小隆德的亡灵和尸骸所拿的锐利刀刃，
        ///
        ///能把敌人切得支离破碎。
        ///
        ///
        ///
        ///受诅咒的武器之一，
        ///
        ///可以伤到亡灵。
        ///武器种类：短剑
        ///
        ///攻击属性：斩击
        ///
        ///
        ///
        ///宽剑身的单刃短剑，
        ///
        ///是盗贼或强盗等匪徒使用的武器。
        ///
        ///
        ///
        ///虽然挥舞时都是挥砍式攻击，
        ///
        ///但格挡后或从背后使出致命一击的威力极高。
        ///武器种类：短剑
        ///
        ///攻击属性：斩击
        ///
        ///
        ///
        ///封印于艾雷米雅斯绘画中的禁忌──
        ///
        ///半龙普利希拉，其尾巴化成的武器。
        ///
        ///稀少的龙武器之一。　        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string AllWeaponDescriptions {
            get {
                return ResourceManager.GetString("AllWeaponDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 万能触媒
        ///誓约武器
        ///匕首
        ///格挡匕首
        ///亡灵小刀
        ///盗贼短刀
        ///普利希拉短剑
        ///短剑
        ///长剑
        ///阔剑
        ///已折断的直剑
        ///巴勒德尔突刺直剑
        ///太阳直剑
        ///刺针直剑
        ///银骑士剑
        ///亚斯特拉直剑
        ///黑暗剑
        ///飞龙剑
        ///直剑剑柄
        ///混种大剑
        ///大剑
        ///蛇人大剑
        ///焰形大剑
        ///石大剑
        ///亚尔特留斯大剑
        ///大王大剑
        ///月光大剑
        ///黑骑士剑
        ///双手巨剑
        ///巨剑
        ///恶魔柴刀
        ///古龙大剑
        ///黑骑士大剑
        ///短弯刀
        ///弯刃大刀
        ///钩剑
        ///亡灵锯齿刀
        ///绘画守护者曲剑
        ///克拉格魔剑
        ///献祭刀
        ///丛云
        ///墓王剑
        ///打刀
        ///晾衣长刀
        ///居合刀
        ///破甲细剑
        ///细剑
        ///刺剑
        ///蓓尔嘉刺剑
        ///里卡尔刺剑
        ///手斧
        ///战斧
        ///弦月斧
        ///切肉菜刀
        ///巨偶斧
        ///石像鬼尾斧
        ///巨斧
        ///恶魔大斧
        ///龙王大斧
        ///黑骑士大斧
        ///棍棒
        ///锤矛
        ///晨星锤
        ///战镐
        ///十字镐
        ///强化棍棒
        ///铁匠铁锤
        ///巨人铁匠木槌
        ///巴摩斯锤子
        ///巨型棍棒
        ///神许重锤
        ///恶魔大锤
        ///大龙牙
        ///大型棍棒
        ///斯摩的锤子
        ///拳头
        ///护手带
        ///钩爪
        ///龙骨拳套
        ///黑暗之手
        ///枪
        ///雁翅枪
        ///游击枪
        ///恶魔枪
        ///传道者三股叉
        ///银骑士枪
        ///矛
        ///猎龙枪
        ///月光蝶触角
        ///戟
        ///巨人戟
        ///楔 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string AllWeaponNames {
            get {
                return ResourceManager.GetString("AllWeaponNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格挡
        ///亡灵
        ///盗贼
        ///普利希拉
        ///短
        ///长
        ///阔
        ///已折断的
        ///巴勒德尔
        ///太阳
        ///刺针
        ///银骑士
        ///亚斯特拉
        ///黑暗
        ///飞龙
        ///混种
        ///蛇人
        ///焰形
        ///石
        ///亚尔特留斯
        ///大王
        ///月光
        ///黑骑士
        ///双手
        ///恶魔
        ///古龙
        ///亡灵锯齿
        ///绘画守护者
        ///克拉格
        ///献祭
        ///墓王
        ///晾衣
        ///破甲
        ///细
        ///蓓尔嘉
        ///里卡尔
        ///手
        ///战
        ///弦月
        ///切肉
        ///巨偶
        ///石像鬼尾
        ///巨
        ///恶魔
        ///龙王
        ///锤
        ///晨星
        ///战
        ///十字
        ///强化
        ///铁匠
        ///巨人铁匠
        ///巴摩斯
        ///巨型
        ///神许
        ///大型
        ///斯摩
        ///拳头
        ///护手带
        ///龙骨
        ///黑暗之手
        ///雁翅
        ///游击
        ///传道者
        ///猎龙
        ///月光蝶
        ///巨人
        ///楔形
        ///石像鬼
        ///鹤嘴
        ///猎命
        ///法里斯
        ///复合
        ///暗月
        ///轻
        ///重
        ///狙击
        ///魔法师
        ///比阿特丽斯
        ///封印
        ///罗根
        ///暗月
        ///乌拉席露白枝
        ///伊札里斯
        ///粗布
        ///索尔隆德
        ///白
        ///双鸟纹木
        ///木
        ///大皮
        ///小皮
        ///小圆
        ///半坏木
        ///皮
        ///木板
        ///双蛇纹圆
        ///熨斗形
        ///骑士
        ///塔纹鸢形
        ///草纹
        ///游魂士兵
        ///巴勒德尔
        ///图纹
        ///龙图纹
        ///战士圆
        ///铁圆
        ///蜘蛛纹
        ///太阳纹
        ///突刺
        ///红白圆
        ///双蛇纹鸢形
        ///巨鹰纹
        ///塔
        ///哈维尔
        ///骸骨车轮        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string AllWeaponNamesNoSuffix {
            get {
                return ResourceManager.GetString("AllWeaponNamesNoSuffix", resourceCulture);
            }
        }
    }
}
